name: Auto Merge on Label

on:
  pull_request_target:
    types: [labeled]

permissions:
  contents: write
  pull-requests: write

jobs:
  auto_merge:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Node.js 20
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      # Conditionally run the next steps only if the "ready-to-merge" label was added
      - name: Check if "ready-to-merge" label was added
        if: ${{ github.event.label.name == "ready-to-merge" }}
        run: echo "ready-to-merge label was added to PR."

      # Setup GitHub CLI
      - name: Setup GitHub CLI
        run: |
          if ! gh --version; then
            sudo apt-get install gh
          fi

      # Authenticate GitHub CLI using GITHUB_TOKEN
      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      # Merge PRs labeled as "ready-to-merge"
      - name: Merge PR labeled as "ready-to-merge"
        if: ${{ github.event.label.name == "ready-to-merge" }}
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          PR_URL=${{ github.event.pull_request.html_url }}
          gh pr merge "$PR_NUMBER" --merge --admin
          echo "Merged PR $PR_NUMBER: $PR_URL"
