name: Scheduled Merge Workflow

on:
  schedule:
    # Runs at 5 PM UTC, which is 9 AM PST (UTC-8)
    - cron: '0 17 * * *'

permissions:
  contents: write
  pull-requests: write

jobs:
  merge_approved_prs:
    runs-on: ubuntu-latest
    steps:
      # Echo the current time for verification
      - name: Echo current time
        run: echo "Running at $(date)"

      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Node.js 20
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Optionally setup GitHub CLI if needed
      - name: Setup GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh

      # Authenticate GitHub CLI
      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      # Merge PRs labeled as 'ready-to-merge'
      - name: Merge PRs labeled as 'ready-to-merge'
        run: |
          gh pr list --label "ready-to-merge" --state open --base main --json number,url |
          jq -r '.[] | .number + " " + .url' |
          while read -r number url; do
            gh pr merge "$number" --merge --admin
            echo "Merged PR $number: $url"
          done
