name: Scheduled Merge

on:
  schedule:
    # Runs at 5 PM UTC, equivalent to 11 AM PT outside DST.
    - cron: '30 7 * * *'

permissions:
  contents: write
  pull-requests: write

jobs:
  merge_approved_prs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup GitHub CLI
      run: |
        if ! gh --version; then
          sudo apt-get install gh
        fi

    - name: Authenticate GitHub CLI
      run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

    - name: Merge PRs labeled as 'ready-to-merge'
      run: |
        gh pr list --label "ready-to-merge" --state open --base main --json number,url |
        jq -r '.[] | .number + " " + .url' |
        while read -r number url; do
          day=$(date +%u)
          if [ "$day" -ge 1 ] && [ "$day" -le 4 ]; then
            gh pr merge "$number" --merge --admin
            echo "Merged PR $number: $url"
          else
            echo "Skipping merge for PR $number: $url, as today is not within the allowed merge window."
          fi
        done